### ISSUE TITLE
Search method syntax is not consistent with benchmarks syntax in configuration file

### ISSUE THREAD

**Issue by wigging** [deephyper/cbbo-benchmarks#3]
The search methods are defined as tables in the configuration file as:

```toml
[search.method.random]
package = "deephyper.hpo"
name = "RandomSearch"

[search.method.cbo_093]
package = "deephyper.hpo"
name = "CBO"
kwargs.acq_optimizer = "ga"

[search.method.cbo]
package = "deephyper.hpo"
name = "CBO"
kwargs.acq_optimizer = "ga"
```

But the benchmarks in the configuration file are defined as an array of tables as shown below:

```toml
[[benchmark]]
name = "Griewank"
nparams = 5
offset = -4
nslack = 0

[[benchmark]]
name = "Hartmann6D"

[[benchmark]]
name = "Levy"
nparams = 5
```

To be consistent, a similar approach should be used for the search method too. A possible solution could be:

```toml
[[search_method]]
name = "RandomSearch"
package = "deephyper.hpo"

[[search_method]]
name = "CBO93"
package = "deephyper.hpo"
kwargs.acq_optimizer = "ga"

[[search_method]]
name = "CBO"
package = "deephyper.hpo"
kwargs.acq_optimizer = "ga"
```
